### ISSUE TITLE
Implement webhook api calls in cli

### ISSUE THREAD

**Issue by pelim** [CopadoSolutions/webhook-cli#3]
map command options to webhook api urls

**Comment by larsenfed** [comment]
Hi there,
This cli does exactly what you are asking for.
@pelim can you provide a description to this issue please?

**Comment by pelim** [comment]
@larsenfed I expect from a cli api client that it wraps api calls in command options i.e. 

Using memorable command option

`$ copado metadata --org <org_id> --secret <api_key>`

 instead of passing the complete webhook url

`$ ./copado.py --url https://copado.herokuapp.com/json/v1/webhook/metadata/org_id?api_key=user_api_key`

**Comment by larsenfed** [comment]
Thanks @pelim, that makes total sense.
Actually we will release a new CLI based on the SFDC CLI, which will have verbs, just like you mentioned.
So, please stay tuned.

Kind regards.-
